### PR TITLE
Fix ESLint errors and enforce ESLint rules by default

### LINKED ISSUE #1: Enable ESLint
Fix lint errors and enable ESLint.

### PR DESCRIPTION
**Pull request by jianjunz**
Fix #1.

### CODE REVIEW

File: src/sdk/base/codec.js [hunk 1]
```diff
@@ -34,7 +34,8 @@ export class AudioCodecParameters {
      * @member {string} name
      * @memberof Owt.Base.AudioCodecParameters
      * @instance
-     * @desc Name of a codec. Please use a value in Owt.Base.AudioCodec. However, some functions do not support all the values in Owt.Base.AudioCodec.
+     * @desc Name of a codec. Please a value in Oms.Base.AudioCodec. However,
```
Comment (HuaChunbo) [inline src/sdk/base/codec.js]: Should this be owt here?

Comment (jianjunz) [reply src/sdk/base/codec.js]: Fixed. Thanks.
